name: Deploy to Google Cloud Storage
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
on:
  push:
    branches:
    - 'main'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0

    - name: 'Copy files to GCS'
      run: './.github/workflows/copy_files_to_gcs.sh'